apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-status
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab-status
  template:
    metadata:
      labels:
        app: homelab-status
    spec:
      serviceAccountName: homelab-status
      nodeSelector:
        kubernetes.io/hostname: pi-control
      containers:
        - name: homelab-status
          image: ghcr.io/malin502/homelab-status:sha-c11fc8defc2d03fce5b8c5988994ba3483edde59
          ports:
            - containerPort: 8080