apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-status
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Malin502/k8s-homelab-platform.git
    targetRevision: main
    path: applications/homelab-status
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true